minor change

diff --git a/bin/dku b/bin/dku
--- a/bin/dku
+++ b/bin/dku
@@ -216,6 +216,7 @@ declare DockerDir
 declare DockerImg
 declare DockerContainer
 declare DockerVolume
+declare runJar
 declare -i DockerTty=1
 declare -i DockerMount=0
 
@@ -236,14 +237,16 @@ commands:
  help              : show this message
  list              : list available builds (aliases)
  build   <alias>   : build an image
+ rebuild <alias>   : rebuild an image
  info    <alias>   : image's information
- [run]   <alias>...: starts a container using image's alias ('run' is optional)
+ [run]   <alias> ..: starts a container using image ('run' is optional)
+ exec    <alias> ..: execute a command inside a running container
+ submit  <alias> ..: submit a jar or an application to a running container
  logs    <alias>   : show container logs
  stop    <alias>   : stop a container  
  start   <alias>   : start a container  
  destroy <alias>   : stop a container and remove associated ressources
  test    <alias>   : test a docker image
- export  <alias> <docker host> : re-tag and export an image
  clean             : cleanup pruned containers 
 "
   quit
@@ -285,7 +288,7 @@ function dockerCheck {
 }
 
 function getDockerImg {
-  [[ $# -eq 0 ]] && usage
+  [[ $# -ge 1 ]] || usage
   arg=$1
   dockerCheck
   # if argument is a directory, use urrent directory as image name
@@ -322,6 +325,21 @@ function getDockerImg {
   # as  well for the volume name
   DockerVolume=${DockerImg}
 }
+
+# pickup the latest assembly Jar for provided application name
+function getJar {
+  [[ $# -ge 2 ]] || usage
+  if [[ -f $2 ]]; then
+    runJar=$2
+    [[ ${runJar##*.} == "jar" ]] || die "$runJar is not a JAR file"
+  else
+    appname=$2
+    runJar=$(find $HOME/.m2 -name "$appname*-assembly.jar" -print0 | xargs -0 ls -t |  head -1)
+    [[ -f $runJar ]] || die "cannot find $appname*-assembly.jar"
+    info "Submitting $runJar"
+  fi
+}
+
 
 function dockerBuild {
   id=$(docker images -q ${DKU_REPO}/${DockerImg} |head -1)
@@ -384,52 +402,53 @@ function dockerRun {
   id=$(docker images -q ${DKU_REPO}/${DockerImg} |head -1)
   [[ -n $id ]] || die "image ${DockerImg} is not built"
   args=$*
-  if [[ $# -eq 0 && $(egrep -c '^ENTRYPOINT' $DockerDir/Dockerfile) -eq 1 ]]
-  then # server mode
-      id=$(docker ps -a | grep "${DockerContainer}\$" | awk '{print $1}')
-       if [[ -n $id ]]
-       then _docker ps | grep -q "${DockerContainer}\$"
-	    if [ $? -eq 0 ]
-	    then warn "Container $DockerImg [$id] already running"
-	    else _docker start $id
-            fi
-	    return
-       fi
-       # first check for usage in label
-       opts=$(dockerInfo | grep "usage:" | head -1 | sed -e "s~usage: docker run ~~;s~ ${DKU_REPO}/${DockerImg}\$~~" )
-       if [[ -n $opts ]]
-       then
-         opts=$(eval echo $opts)
-       else
-         opts="-d --name ${DockerContainer} --network $DKU_NETWORK_"
+  if [[ $# -eq 0 && $(egrep -c '^ENTRYPOINT' $DockerDir/Dockerfile) -eq 1 ]] ; then 
+    # server mode
+    id=$(docker ps -a | grep "${DockerContainer}\$" | awk '{print $1}')
+    if [[ -n $id ]]; then 
+      _docker ps | grep -q "${DockerContainer}\$"
+      if [ $? -eq 0 ]; then 
+	warn "Container $DockerImg [$id] already running"
+      else 
+	_docker start $id
+      fi
+      return
+    fi
+    # first check for usage in label
+    opts=$(dockerInfo | grep "usage:" | head -1 | sed -e "s~usage: docker run ~~;s~ ${DKU_REPO}/${DockerImg}\$~~" )
+    if [[ -n $opts ]]; then
+      opts=$(eval echo $opts)
+    else
+      opts="-d --name ${DockerContainer} --network $DKU_NETWORK_"
          volume=$(egrep '^VOLUME' $DockerDir/Dockerfile | awk '{print $2}')
          [[ -n $volume ]] && opts="$opts --mount source=${DockerVolume},target=$volume"
-         for port in $(egrep '^EXPOSE ' $DockerDir/Dockerfile | cut -c 8-)
-         do grep -q '[$]' <<<$port
-	  if [[ $? -ne 0 ]]
-	  then opts="$opts -p $port:$port"
-	  else
-	    for ev in $(egrep '^ENV .*PORT' $DockerDir/Dockerfile | awk '{print "port=${port/\\$\\{" $2 "\\}/" $3 "}" }')
-	    do eval $ev
-            done
-	    # echo "DEBUG: port=$port"
-	    opts="$opts -p $port:$port"
-	  fi
+         for port in $(egrep '^EXPOSE ' $DockerDir/Dockerfile | cut -c 8-); do
+	   grep -q '[$]' <<<$port
+	   if [[ $? -ne 0 ]]; then 
+	     opts="$opts -p $port:$port"
+	   else
+	     for ev in $(egrep '^ENV .*PORT' $DockerDir/Dockerfile | awk '{print "port=${port/\\$\\{" $2 "\\}/" $3 "}" }')
+	     do eval $ev
+             done
+	     # echo "DEBUG: port=$port"
+	     opts="$opts -p $port:$port"
+	   fi
          done
          for e in $(env | egrep '^[A-Z_]*=' | egrep -v '^PATH=' | cut -d= -f1)
-         do egrep -q "^ENV $e " $DockerDir/Dockerfile && opts="$opts -e $e=${!e}"
+	 do egrep -q "^ENV $e " $DockerDir/Dockerfile && opts="$opts -e $e=${!e}"
          done
-       fi
-       # Check for addtional @RUNOPTS@ 
-       grep -q '# @RUNOPTS@' $DockerDir/Dockerfile && opts="$opts "$(grep '# @RUNOPTS@' $DockerDir/Dockerfile | cut -c 12-)
-       args=""
+    fi
+    # Check for addtional @RUNOPTS@ 
+    grep -q '# @RUNOPTS@' $DockerDir/Dockerfile && opts="$opts "$(grep '# @RUNOPTS@' $DockerDir/Dockerfile | cut -c 12-)
+    args=""
   else # command mode
-       opts="-i --rm --network $DKU_NETWORK_"
-       if [[ $DockerMount -eq 1 ]] 
-       then volume=$(egrep '^VOLUME' $DockerDir/Dockerfile | awk '{print $2}')
+    # if the first argument is an application name, push the JAR to container
+    opts="-i --rm --network $DKU_NETWORK_"
+    if [[ $DockerMount -eq 1 ]] 
+    then volume=$(egrep '^VOLUME' $DockerDir/Dockerfile | awk '{print $2}')
 	    [[ -n $volume ]] && opts="$opts --mount source=${DockerVolume},target=$volume"
-       fi
-     [[ $DockerTty -eq 1 ]] && opts="-t $opts"       
+    fi
+    [[ $DockerTty -eq 1 ]] && opts="-t $opts"       
   fi
   _docker run $opts ${DKU_REPO}/$DockerImg $args
 }
@@ -439,8 +458,14 @@ function dockerExec {
   if [[ -z $id ]]; then
     warn "Container ${DockerContainer} not running"
     return 1
-  else 
+  fi 
+  shift
+  if [[ -n $runJar ]]; then
     shift
+    dockJar=/tmp/${runJar##*/}
+    docker cp $runJar $id:$dockJar
+    _docker exec $id entrypoint.sh submit $dockJar $@
+  else
     _docker exec $id $@
   fi
 }
@@ -477,6 +502,7 @@ function dockerDestroy {
 }
 
 function dockerRebuild {
+  _Opts[f]=1
   dockerDestroy
   dockerBuild
   dockerRun
@@ -594,6 +620,7 @@ case $Command in
   list)     listBuilds;;
   build)    getDockerImg $Arguments; dockerBuild;;
   run)      getDockerImg $Arguments; dockerRun ${Arguments/$DockerImg/};;
+  submit)   getDockerImg $Arguments; getJar $Arguments; dockerExec $Arguments;;
   destroy)  getDockerImg $Arguments; dockerDestroy;;
   start)     getDockerImg $Arguments; dockerStart;;
   stop)     getDockerImg $Arguments; dockerStop;;
