minor change

diff --git a/bin/dku b/bin/dku
--- a/bin/dku
+++ b/bin/dku
@@ -233,7 +233,8 @@ commands:
  info    <alias>   : image's information
  [run]   <alias>...: starts a container using image's alias ('run' is optional)
  logs    <alias>   : show container logs
- stop    <alias>   : stop a container 
+ stop    <alias>   : stop a container  
+ start   <alias>   : start a container  
  destroy <alias>   : stop a container and remove associated ressources
  test    <alias>   : test a docker image
  clean             : cleanup pruned containers 
@@ -297,7 +298,7 @@ function getDockerImg {
 }
 
 function dockerBuild {
-  id=$(docker images -q ${DockerImg} |head -1)
+  id=$(docker images -q dku/${DockerImg} |head -1)
   if [[ -n $id ]]; then
     warn "Image $DockerImg [$id] already built"
     opt f || return
@@ -317,12 +318,11 @@ function dockerBuild {
   # cache the files
   opt c
   if [[ $? -eq 0 ]]; then
-    site=$(grep 'ARG SITE_DOWNLOAD=' docker/hbase/Dockerfile  | cut -d= -f2)
-    [[ -n $site ]] || die "Dockerfile is not using SITE_DOWNLOAD as ARG"
-    url=$(grep '${SITE_DOWNLOAD}' $DockerDir/Dockerfile |  sed -e "s/.*\${SITE_DOWNLOAD}//;s/ .*//;s/\${.*}/$vers/")
-    echo $site/$url
-    # 
-    exit
+    site=$(grep 'ARG HTTP_MIRROR=' $DockerDir/Dockerfile  | cut -d= -f2)
+    [[ -n $site ]] || die "Dockerfile is not using HTTP_MIRROR as ARG"
+    ip=$(getent hosts $DOCKER_HOST | awk '{ print $1 }')
+    export PROXY_BYPASS=$PROXY_BYPASS,$ip
+    export HTTP_MIRROR=http://$ip/files
   fi
   # check if this a  server or an intermediate image
   egrep -q '^ENTRYPOINT' $DockerDir/Dockerfile
@@ -366,7 +366,7 @@ function dockerRun {
 	    return
        fi
        # first check for usage in label
-       opts=$(dockerInfo | grep Usage: | sed -e "s/Usage: docker run //;s/ ${DockerImg}\$//" )
+       opts=$(dockerInfo | grep Usage: | sed -e "s~Usage: docker run ~~;s~ dku/${DockerImg}\$~~" )
        if [[ -n $opts ]]
        then
          opts=$(eval echo $opts)
@@ -410,6 +410,15 @@ function dockerStop {
   then warn "Container ${DockerContainer} not running"
        return 1
   else _docker stop $id
+  fi
+}
+
+function dockerStart {
+  id=$(docker ps -a | grep "${DockerContainer}\$" | awk '{print $1}')
+  if [[ -z $id ]]
+  then warn "Container ${DockerContainer} not found"
+       return 1
+  else _docker start $id
   fi
 }
 
@@ -538,6 +547,7 @@ case $Command in
   build)    getDockerImg $Arguments; dockerBuild;;
   run)      getDockerImg $Arguments; dockerRun ${Arguments/$DockerImg/};;
   destroy)  getDockerImg $Arguments; dockerDestroy;;
+  start)     getDockerImg $Arguments; dockerStart;;
   stop)     getDockerImg $Arguments; dockerStop;;
   test)     getDockerImg $Arguments; dockerTest;;
   logs)     getDockerImg $Arguments; dockerLogs;;
